version: 2

run:
  timeout: 3m

linters:
  disable-all: true
  enable:
    - errcheck
    - govet
    - ineffassign
    - revive
    - staticcheck
    - unused
    - misspell

linter-settings:
  revive:
    rules:
      - name: exported
        disabled: true
      - name: var-naming
        disabled: true

issues:
  exclude-use-default: false
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
    - path: internal/http/
      linters:
        - revive
      text: "var-naming:"

