run:
  timeout: 3m

linters:
  disable-all: true
  enable:
    - errcheck
    - govet
    - ineffassign
    - revive
    - staticcheck
    - typecheck
    - unused
    - goimports
    - gofumpt
    - misspell

linter-settings:
  revive:
    rules:
      - name: exported
        disabled: true

issues:
  exclude-use-default: false

